/*
 * This source file was generated by the Gradle 'init' task
 */
package io.hexlet;

import org.junit.jupiter.api.Test;

import io.hexlet.cv.App;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        var obj = new App();
        // assertNotNull(obj.getGreeting(), "app should have a greeting");
    }
}
